# Generated by Django 5.1.1 on 2025-02-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fcmtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMToken',
        ),
    ]
