# Generated by Django 5.1.1 on 2024-10-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0003_alter_plant_created_at_alter_plant_maximun_humidity_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_name', models.CharField(max_length=100)),
                ('ubication', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartpots', to='plants.plant')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartpots', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.PositiveIntegerField()),
                ('ligth_level', models.PositiveIntegerField()),
                ('water_level', models.PositiveIntegerField()),
                ('registed_at', models.DateTimeField(auto_now=True)),
                ('smart_pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SensorsData', to='smartpots.smartpot')),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximun_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimun_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximun_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minumun_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximun_ligth_level', models.PositiveIntegerField()),
                ('minimun_ligth_level', models.PositiveIntegerField()),
                ('notifications_is_activated', models.BooleanField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='plants.plant')),
                ('smartpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartpot', to='smartpots.smartpot')),
            ],
        ),
        migrations.CreateModel(
            name='WateringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_amount', models.PositiveIntegerField()),
                ('watering_date', models.DateTimeField(auto_now=True)),
                ('smart_pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wateringEvents', to='smartpots.smartpot')),
            ],
        ),
    ]
