# Generated by Django 5.1.1 on 2024-10-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='ligth_level',
            new_name='light_level',
        ),
    ]
