# Generated by Django 5.1.1 on 2024-11-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpots', '0005_smartpot_serial_number_alter_smartpot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartpot',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
