# Generated by Django 5.1.1 on 2024-11-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpots', '0006_alter_smartpot_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('eventoRiego', 'Evento de Riego'), ('peligroNulo', 'Peligro Nulo'), ('peligroModerado', 'Peligro Moderado'), ('peligroAlto', 'Peligro Alto')], default='peligroNulo', max_length=20)),
                ('alert_content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('smartpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='smartpots.smartpot')),
            ],
        ),
    ]
