# Generated by Django 5.1.1 on 2024-11-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpots', '0007_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurations',
            old_name='minumun_humidity',
            new_name='minimun_humidity',
        ),
        migrations.AlterField(
            model_name='configurations',
            name='notifications_is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
