# Generated by Django 5.1.1 on 2024-12-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpots', '0008_rename_minumun_humidity_configurations_minimun_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsdata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
