# Generated by Django 5.1.1 on 2024-10-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ideal_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ideal_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sunlight_needs', models.CharField(max_length=100)),
                ('watering_frequency', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
