# Generated by Django 5.1.1 on 2024-10-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_humidity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ideal_temperature',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='sunlight_needs',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='watering_frequency',
        ),
        migrations.AddField(
            model_name='plant',
            name='maximun_humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='maximun_ligth_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='maximun_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='minimun_ligth_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='minimun_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='minumun_humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_cares',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
