# Generated by Django 5.1.1 on 2024-10-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plant_description_remove_plant_ideal_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='maximun_humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='maximun_ligth_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='maximun_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='minimun_ligth_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='minimun_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='minumun_humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_cares',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
