# Generated by Django 5.1.1 on 2024-10-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_created_at_alter_plant_maximun_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='plant_cares',
        ),
        migrations.CreateModel(
            name='PlantRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=8)),
                ('recommendation', models.CharField(max_length=255)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='plants.plant')),
            ],
        ),
    ]
