# Generated by Django 5.1.1 on 2024-11-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_plant_plant_cares_plantrecomendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='minumun_humidity',
            new_name='minimun_humidity',
        ),
    ]
