# Generated by Django 5.1.1 on 2024-11-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_rename_minumun_humidity_plant_minimun_humidity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantrecomendation',
            old_name='recommendation',
            new_name='content',
        ),
    ]
